apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-apigateway
  namespace: dev
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: dev-apigateway
  template:
    metadata:
      labels:
        app: dev-apigateway
    spec:
      containers:
        - name: dev-apigateway
          image: registry.robotov.site/dev-apigateway:fc69d98
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: library-secrets
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: library-secrets
                  key: REDIS_PORT
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: library-secrets
                  key: REDIS_PASSWORD
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "768Mi"
              cpu: "500m"
